name: Release Github Dev Package

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          name: recheck-cli-${{ steps.package-version.outputs.current-version}}
          tag_name: ${{ steps.package-version.outputs.current-version}}
